### ISSUE TITLE
[BUG] Unable to install `anonympy` on Ubuntu

### ISSUE THREAD

**Issue by fbvdka** [ArtLabss/open-data-anonymizer#25]
**Describe the bug**
I am not able to install anonympy with python 3.10

**To Reproduce**
1. install pyhton 3.10
2. `pip install anonympy`

I get 
```
Collecting anonympy
  Downloading anonympy-0.3.7.tar.gz (5.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.8/5.8 MB 6.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in anonympy setup command: 'python_requires' must be a string containing valid version specifiers; Invalid specifier: '>=3.6*'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Expected behavior**
It must be installed without any error

**Desktop (please complete the following information):**
 - OS: Linux ubuntu

**Additional context**

**Comment by shukkkur** [comment]
@fbvdka Hi!) 
Yep, `pip install anonympy` works perfectly on Windows, however on Linux I also get an error (tried on Google Colab)
Try the following:
1) `git clone https://github.com/ArtLabss/open-data-anonymizer.git`
2) `cd open-data-anonymizer`
3) `pip install .`

Worked on Colab. Anyway good luck!)

**Comment by fbvdka** [comment]
Perfect! That works.

**Comment by samuelstuetz** [comment]
There should be another release. This bug seems to be related to a pip update where they switched to regex parsing in preparation for future PEP changes. It does not break in many cases where it is a >3.6.* however the 3.6* won't fly. The code is already fixed but having to clone and then install manually whatever is the current main branch status is not a good solution. Nor is installing an older pip.
Could someone with more insight to current repo status release a new version.
